### ISSUE TITLE
support set registry for other images example `postInstallJob` or `preInstallJob` 

### ISSUE THREAD

**Issue by calvin0327** [DaoCloud/karmada-operator1#47]
/kind feature

Currently, we can not set registry for karmada postInstallJob and preInstallJob image in chart.
https://github.com/karmada-io/karmada/pull/2348/files
the pr had merged,  wo should update synchronously.

**Comment by lixingchenDaoCloud** [comment]
https://github.com/DaoCloud/karmada-operator/pull/63
